### ISSUE TITLE
STFT Parameters

### ISSUE THREAD

**Issue by zinengtang** [haoheliu/AudioLDM#10]
I tried to reproduce the audio spectrogram processing settings in the paper.
Is this the correct one?
<img width="401" alt="Screen Shot 2023-02-09 at 12 31 51 AM" src="https://user-images.githubusercontent.com/82334223/217726675-58841d66-8890-4f75-8322-018dd1c1bb24.png">

**Comment by haoheliu** [comment]
Yes that's correct

**Comment by zinengtang** [comment]
thank you!

**Comment by zinengtang** [comment]
I wrote audio preprocessing script like this is it correct? @haoheliu 

```
import torchaudio
audio_wavs, sr = torchaudio.load('../../../data/audioset/data/balanced_train_segments/audio/--aE2O5G5WE_0_10000.flac')
audio_wavs = torchaudio.functional.resample(waveform=audio_wavs, orig_freq=sr, new_freq=16000).mean(0).unsqueeze(0)

from audioldm.audio.tools import get_mel_from_wav
from audioldm.audio.stft import TacotronSTFT
stft = TacotronSTFT(filter_length=1024,
        hop_length=160,
        win_length=1024,
        n_mel_channels=64,
        sampling_rate=16000,
        mel_fmin=0,
        mel_fmax=8000,)
x, _, _ = get_mel_from_wav(audio_wavs.squeeze(), stft)
```

where x is the input to VAE encoder.

**Comment by haoheliu** [comment]
@zinengtang  Looks good to me. I think it's correct.
