### ISSUE TITLE
Is there any docs on how to run the Text to Speech?

### ISSUE THREAD

**Issue by DamienDeepgram** [haoheliu/AudioLDM#103]
I saw there are example outputs [here](https://audioldm.github.io/audioldm2/#section_3)

But there is no info how to run Text to Speech in the documentation

eg.

In a man's voice say "hello world"
In a women's say "hello world"

**Comment by olaviinha** [comment]
I think this is the wrong repository.

https://github.com/haoheliu/audioldm2 has text-to-speech in todo list.

**Comment by DamienDeepgram** [comment]
Yes sorry thanks for catching that
