### ISSUE TITLE
Google Colab

### ISSUE THREAD

**Issue by aeiouaeiouaeiouaeiouaeiouaeiou** [haoheliu/AudioLDM#11]
Hugging Face web demo at this moment is failing to output the result as a video file. Are there any plans to add Google Colab notebook in the repository?

**Comment by haoheliu** [comment]
Here is a google colab demo made by [@TeuthisDreams](https://twitter.com/TeuthisDreams): https://twitter.com/TeuthisDreams/status/1621324351420403712. Maybe of interest?

**Comment by haoheliu** [comment]
Also, I add a badge on the top of the readme in case you need it.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
It looks like they forgot to add a step for preinstalling packages:

![2023-02-12_08-57-00](https://user-images.githubusercontent.com/69355938/218296099-09543b0e-55bd-4af7-ad55-0ee11dec147c.png)

Nevertheless, the HF web demo works again for me.

**Comment by olaviinha** [comment]
I have a functioning Colab for this also, in case interested:
https://colab.research.google.com/github/olaviinha/NeuralTextToAudio/blob/main/AudioLDM_pub.ipynb

**Comment by haoheliu** [comment]
@olaviinha Looks nice. Can I use the link to your colab notebook in the badge of this repo so that people can play with it?

**Comment by olaviinha** [comment]
Sure, feel free!

**Comment by olaviinha** [comment]
@haoheliu Hey, it just occurred to me that would you mind adding parameter `?force_dark=true` to the colab link? I use some color codes in the outputs that may be too bright for light theme.

P.S. Style transfer has been added to notebook as well.

**Comment by haoheliu** [comment]
@olaviinha Will do. Fantastic thanks!
