### ISSUE TITLE
Error: 	Unexpected key(s) in state_dict: "cond_stage_model.model.text_branch.embeddings.position_ids". 

### ISSUE THREAD

**Issue by buscon** [haoheliu/AudioLDM#117]
When I try to use audioLDM on Colab I run into the following error:
# I first install audioldm
!pip3 install audioldm
# when I try to run it, I get the following error:
!audioldm -t "A hammer is hitting a wooden surface"

`
Load AudioLDM: %s audioldm-m-full
DiffusionWrapper has 415.95 M params.
/usr/local/lib/python3.10/dist-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
/usr/local/lib/python3.10/dist-packages/torchlibrosa/stft.py:193: FutureWarning: Pass size=1024 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  fft_window = librosa.util.pad_center(fft_window, n_fft)
/usr/local/lib/python3.10/dist-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "/usr/local/bin/audioldm", line 152, in <module>
    audioldm = build_model(model_name=args.model_name)
  File "/usr/local/lib/python3.10/dist-packages/audioldm/pipeline.py", line 86, in build_model
    latent_diffusion.load_state_dict(checkpoint["state_dict"])
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LatentDiffusion:
	Unexpected key(s) in state_dict: "cond_stage_model.model.text_branch.embeddings.position_ids".
 `

**Comment by haoheliu** [comment]
This looks like the version of the transformers it not matched. I'll have a quick test on my end and try to fix that

**Comment by haoheliu** [comment]
@buscon Could you please double check if you are using transformers==4.30.2?

**Comment by buscon** [comment]
yes, thank you, with version 4.30.2 it does work now.
