### ISSUE TITLE
Hope to release the training code

### ISSUE THREAD

**Issue by zhanganny** [haoheliu/AudioLDM#118]
Hello, could you please release the training code now. Your work is remarkable and hope the code will be released soon. That will be a fantastic thing! Thank you and looking forward to your reply.

**Comment by Tortoise17** [comment]
Please check this 
`https://github.com/haoheliu/AudioLDM-training-finetuning`
I hope this works for you.

**Comment by zhanganny** [comment]
> Please check this `https://github.com/haoheliu/AudioLDM-training-finetuning` I hope this works for you.

Thanks！！
