### ISSUE TITLE
pip package doesn't work

### ISSUE THREAD

**Issue by Astra060** [haoheliu/AudioLDM#18]
It seems like the package is missing files, or at least I think. command prompt does not work as it is. 

command:
python -m audioldm

error I got:
No module named audioldm.__main__; 'audioldm' is a package and cannot be directly executed

everything is installed. when something is missing, it does show errors, however when it should run, it doesn't

**Comment by haoheliu** [comment]
@Astra060  Hi, may be you can try to change the directory where you run the code, making sure not in the root directory of this repo.

**Comment by haoheliu** [comment]
And I update the file a bit. You can reinstall the 0.0.9 version audioldm to see if that helps.

**Comment by haoheliu** [comment]
If you use Linux or macOS you can directory run 
```
audioldm
```
instead of using
```
python3 -m audioldm
```

**Comment by Astra060** [comment]
hello, thanks, fixed with 0.0.9
