### ISSUE TITLE
Stuck at "downloading the main structure of audioldm"

### ISSUE THREAD

**Issue by zvonimir-rezo** [haoheliu/AudioLDM#20]
Following the instructions for running app.py through terminal, after I run "python3 app.py" I get:
Downloading the main structure of audioldm

And then it gets stuck. I tried running "rm ~/.cache/audioldm/audioldm-s-full.ckpt" and using pip and python instead of pip3 and python3 just in case but it didn't help.

**Comment by jacksonlevine** [comment]
Hey, why did you close this? Any solution? I am also here. It is stuck at 99%
