### ISSUE TITLE
I try to make with different prompts audio using transfer mode but it seems that output audio is empty

### ISSUE THREAD

**Issue by tonymacx86PRO** [haoheliu/AudioLDM#31]
Input: "Any text prompt"
Duration: I tried 40,45,70
Result: AudioLDM gives me for example 40 second audio without any sound
**How to solve this?**
But when i generate 10 second generation it seems to work, why?

**Comment by haoheliu** [comment]
@tonymacx86PRO Hi could you please provide your linux command for that issue?

I just tested with the following command and the result looks fine to me:
```shell
audioldm --mode "transfer" --file_path trumpet.wav -t "Children Singing" 
```

**Comment by tonymacx86PRO** [comment]
audioldm --mode "transfer" -f mpmn.wav -t "Acapella" -dur 20
audioldm --mode "transfer" -f mpmn.wav -t "Drum kit and flute" -dur 10
audioldm --mode "transfer" -f mpmn.wav -t "Drum kit and flute" -dur 40

**Comment by haoheliu** [comment]
@tonymacx86PRO how long is the audio file mpmn.wav?

**Comment by tonymacx86PRO** [comment]
It's also very strange that sometimes I have an empty generation without CUDA errors, but when I tried 70 seconds again, he said you don't have 3 GB of video memory

**Comment by haoheliu** [comment]
OK thanks for reporting this. I'll look into it now.

**Comment by haoheliu** [comment]
@tonymacx86PRO AudioLDM is quite an initial version of Text-to-Audio. There is still a lot yet to improve. So may be better to lower the expectation a bit. :)

**Comment by haoheliu** [comment]
@tonymacx86PRO I've spotted some problems in the code, but haven't found the root cause. For now, you can safely play with AudioLDM with a duration smaller than 20 seconds. Please reinstall the latest version of audioldm via pip and try again. Thanks.

**Comment by haoheliu** [comment]
BTW latest version is 0.0.17

**Comment by tonymacx86PRO** [comment]
git pull (repo) & pip install --upgrade audioldm
Console input and output
```
(audioldm) C:\Users\Coder\Documents\AI\AudioLDM>audioldm -f mpmn.wav --mode "transfer" -t "Acapella" -dur 20
DiffusionWrapper has 185.04 M params.
C:\Users\Coder\.conda\envs\audioldm\lib\site-packages\torchlibrosa\stft.py:193: FutureWarning: Pass size=1024 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  fft_window = librosa.util.pad_center(fft_window, n_fft)
C:\Users\Coder\.conda\envs\audioldm\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\TensorShape.cpp:3191.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Some weights of the model checkpoint at roberta-base were not used when initializing RobertaModel: ['lm_head.bias', 'lm_head.dense.bias', 'lm_head.layer_norm.weight', 'lm_head.dense.weight', 'lm_head.decoder.weight', 'lm_head.layer_norm.bias']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
C:\Users\Coder\Documents\AI\AudioLDM\audioldm\audio\stft.py:42: FutureWarning: Pass size=1024 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  fft_window = pad_center(fft_window, filter_length)
C:\Users\Coder\Documents\AI\AudioLDM\audioldm\audio\stft.py:145: FutureWarning: Pass sr=16000, n_fft=1024, n_mels=64, fmin=0, fmax=8000 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel_basis = librosa_mel_fn(
Decoding image: 100%|████████████████████████████████████████████████████████████████| 100/100 [00:10<00:00,  9.14it/s]
Save audio to ./output\transfer\mpmn\01_03_2023_15_05_16_Acapella_0.wav
```
Another empty file

**Comment by tonymacx86PRO** [comment]
Oh maybe choose 17.5 seconds

**Comment by haoheliu** [comment]
@tonymacx86PRO  Oh, that's bad. Sorry about that. I'll keep looking into it. Also can you please share your audio file so that I can test on my side?

**Comment by haoheliu** [comment]
Looks like there are some numerical problems in the VAE decoder that lead to NAN output. Will try to solve it today.

**Comment by tonymacx86PRO** [comment]
[01_03_2023_15_11_15_Acapella_0.zip](https://github.com/haoheliu/AudioLDM/files/10863644/01_03_2023_15_11_15_Acapella_0.zip)

**Comment by haoheliu** [comment]
> I am sended in zip because i can't send wav [01_03_2023_15_11_15_Acapella_0.zip](https://github.com/haoheliu/AudioLDM/files/10863644/01_03_2023_15_11_15_Acapella_0.zip)

Hi I mean sharing the mpmn.wav

**Comment by tonymacx86PRO** [comment]
First of all, I sent a file named DK_-_MP_Main_Menu right now because a friend asked me to leave it, but it's an mpmn.wav file
And the original file was in ogg and I threw the converted file to wav to the neural network, I don't know if there may be a converter problem, but here are the files.
[DK_-_MP_Main_Menu.zip](https://github.com/haoheliu/AudioLDM/files/10872148/DK_-_MP_Main_Menu.zip)

**Comment by haoheliu** [comment]
> First of all, I sent a file named DK_-_MP_Main_Menu right now because a friend asked me to leave it, but it's an mpmn.wav file And the original file was in ogg and I threw the converted file to wav to the neural network, I don't know if there may be a converter problem, but here are the files. [Original (*.ogg) and Converted (*.wav)](https://github.com/haoheliu/AudioLDM/files/10872148/DK_-_MP_Main_Menu.zip)

Thanks I'll look into it.

**Comment by tonymacx86PRO** [comment]
How is it going?

**Comment by haoheliu** [comment]
@tonymacx86PRO Should work now. But still shorter duration may yield better results.

**Comment by tonymacx86PRO** [comment]
What audio formats support CLI?

**Comment by haoheliu** [comment]
.wav file will work

**Comment by tonymacx86PRO** [comment]
I will check out your fix
Reply: .wav file will work; Ok

**Comment by tonymacx86PRO** [comment]
20 seconds is working but token "Acapella" doesn't do the best. My music is not appear acapella, i don't know i will try man voice

**Comment by haoheliu** [comment]
Yes, the model does not guarantee good results. It might need some tuning on transfer_strength, seed, text, etc.

**Comment by tonymacx86PRO** [comment]
Man voice very similar

**Comment by tonymacx86PRO** [comment]
I'm going to rest well I think it's time to close this issue

**Comment by tonymacx86PRO** [comment]
I will look paper to understand the prompting of this model
