### ISSUE TITLE
Chartdet dependency is missing from site-packages

### ISSUE THREAD

**Issue by rne1223** [haoheliu/AudioLDM#39]
Running audioldm commandline interface on and Windows 10 machine this error appeared:

import chardet 
ModuleNotFoundError: No module named 'chardet'

I was able to resolved the issue by installing chardet package with `pip3 install chardet`, but i belive that the dependency needs to be added to the site packages: https://stackoverflow.com/questions/51775462/python-3-7-import-requests-returns-chardet-error

**Comment by haoheliu** [comment]
Thanks for reporting. Dependency is added to the setup.py
