### ISSUE TITLE
CUFFT_INTERNAL_ERROR

### ISSUE THREAD

**Issue by Limbicnation** [haoheliu/AudioLDM#49]
When attempting to run app.py, an error is returned.
``   return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
RuntimeError: cuFFT error: CUFFT_INTERNAL_ERROR``

**Comment by 510043149** [comment]
use cuda 11.8 version pytorch will resolve this issue, this issue also arises at my RTX4090

**Comment by Limbicnation** [comment]
Thank you. In my case, I had to install PyTorch with Conda using the following command:

`conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia`
