### ISSUE TITLE
No module named 'audioldm'

### ISSUE THREAD

**Issue by YooPita** [haoheliu/AudioLDM#6]
I did everything according to the instructions, but I still ran into this problem.

my system is windows 11

then ran the command:
python3 scripts/text2sound.py -t "A hammer is hitting a wooden surface"

the error i got:
Traceback (most recent call last):
  File "**path-to-directory**\scripts\text2sound.py", line 2, in <module>
    from audioldm import text_to_audio, build_model, save_wave
ModuleNotFoundError: No module named 'audioldm'

**Comment by haoheliu** [comment]
Sorry about that. I'll now make AudioLDM into a pip installable package. Will probably fix that.

**Comment by haoheliu** [comment]
Close this issue for now. Feel free to reopen if the issue still exists.
