### ISSUE TITLE
Request: Enable device "cpu" support for experimental purposes

### ISSUE THREAD

**Issue by trholding** [haoheliu/AudioLDM#77]
I intend to experiment with this on a CPU only server, could you enable "cpu" support for the same. I am aware that generation can take long time. But its good for benchmarking. Tango for example took me 107 minutes on 4 cores.

**Comment by haoheliu** [comment]
Sorry, we currently do not have plans for adding CPU support since the process could be very slow. I would suggest using google collab, which has free GPU.
